# Hariom Singhal Puri 

In [4]:
import numpy as np
# How to Create 1D array.
list = [1,2,3,4,5]
arr = np.array(list)   # this is a 1D Array
print(arr)

[1 2 3 4 5]


In [6]:
type(arr)   # Type check krne ke liye

numpy.ndarray

In [10]:
# How to Create Multi-Dimensional or We can Say 2D array
list1 = [11,12,13,15,16]
list2 = [25,26,27,28,29]
list3 = [32,33,34,36,39]
arr1 = np.array([list1,list2,list3])
print(arr1)

[[11 12 13 15 16]
 [25 26 27 28 29]
 [32 33 34 36 39]]


In [12]:
arr1.shape    # This Will Tell You What is the Shape or We can Say Dimension of an Array
# Remembers Arrays Rows and Columns always counted from 0 .

(3, 5)

In [14]:
# Changing the index of an array.
arr[2] = 9    # for our 1D array.
print(arr)
arr1[2,1] = 12   # For our 2D array.
print(arr1)

[1 2 9 4 5]
[[11 12 13 15 16]
 [25 26 27 28 29]
 [32 12 34 36 39]]


In [16]:
arr  # First We have to call our 1D array.

array([1, 2, 9, 4, 5])

In [15]:
# Indexing in 1D array or arr
print(arr[2])    # This will Directly tell what is the 3rd index in our 1st array.
print(arr[2:])   # This will print the indexs from 3rd index to last index for 1D array.
print(arr[::-1]) # This Will print a new Array which is reverse from the Previous one.
print(arr[::2])  # This will give you a list in which indexes jumping in multiple of 2. 

9
[9 4 5]
[5 4 9 2 1]
[1 9 5]


In [19]:
arr1   # First We have to call our 2D array.

array([[11, 12, 13, 15, 16],
       [25, 26, 27, 28, 29],
       [32, 12, 34, 36, 39]])

In [21]:
# Indexing in 2D array or arr1
print(arr1[2,1])  # This will tell you what is in the index of {3,2} for arr1. 
print(arr1[:,1])  # This Will Give you a new array of complete 1 column of arr1.
print(arr1[1,:])  # This Will Give You a new array of complete 1 row of arr1.

12
[12 26 12]
[25 26 27 28 29]


In [23]:
# using 1:  >>> this will del all items or we can we it will take all items except 1 row 
# using 1:3 >>> this will give us elements which are present on 1-2 in that column. 
print(arr1[1: ,1:3])  # This will Give you a 2D array of 

[[26 27]
 [12 34]]


In [25]:
# using 2:   >>> this will del all items except 3rd row.
# using 2:5  >>> this will give us elemnts from 2 to 4 from 3rd column.
print(arr1[2: ,2:5])

[[34 36 39]]


In [27]:
# using :   >>> this will take all the items from 0 to 2 row.
# using 3:  >>> this will give us elemnts from .
print(arr1[:,3:]) 

[[15 16]
 [28 29]
 [36 39]]


In [29]:
# using :   >>> this will take all the items from 0 to 2 row.
# using 0: :4  >>> this will give us elemnts from 1st coloumn and last column.
print(arr1[:,0::4])

[[11 16]
 [25 29]
 [32 39]]


In [31]:
arr  # This will print our New Array.

array([1, 2, 9, 4, 5])

In [33]:
# If want a array from our arr which is greater than 2 then:
print(arr>2)    # This will give us Booleans values 
arr[arr>2]      # This will create a new array only elements which is greater than 2.

[False False  True  True  True]


array([9, 4, 5])

In [35]:
# Changing the dimension of arr1 (3X5) to (5X3)
arr1.reshape(5,3)

array([[11, 12, 13],
       [15, 16, 25],
       [26, 27, 28],
       [29, 32, 12],
       [34, 36, 39]])

In [37]:
# Creating a 1D array
arr2 = np.arange(1,16,2)  # Numpy Directly create a array by user choice.
print(arr2)

# Now we can also reshape the array by our choice.
arr3 = arr2.reshape(2,4)    # reshaping into dimension of 2X4.
print(arr3)               
arr4 = arr2.reshape(4,2)    # Reshaping into dimension of 4X2
print(arr4)               

[ 1  3  5  7  9 11 13 15]
[[ 1  3  5  7]
 [ 9 11 13 15]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [39]:
# Yes Bhai !!!!
arr5 = arr*arr  # our 1st array is multiply by itself and give us a new array.
print(arr5)
arr6 = arr *2   # our 1st array is multiply by 2 and give us a new array.
print(arr6)

[ 1  4 81 16 25]
[ 2  4 18  8 10]


In [41]:
# Yes Bro !!!
arr7 = np.ones((3,3))
print(arr7)
arr8 = np.zeros((3,3))
print(arr8)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [43]:
# Kya bolu....Yes !!!
# Generate kro aur reshape kro !!! Set Hai Boss.
np.random.randint(1,100,25).reshape(5,5)

array([[25, 33, 62, 13, 73],
       [38, 48,  7, 42, 69],
       [38, 12, 49, 60, 45],
       [85, 76, 46, 73,  2],
       [44, 94, 91, 98, 27]])