In [3]:
import pandas as pd
import numpy as np

In [5]:
# Create a Random array and then reshape.
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [9]:
# Pattern to Draw a DataFrame. 
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index = ["row1","row2","row3","row4","row5"],columns= ["Column1","Column2","Column3","Column4"])

In [11]:
df.head()

Column1  Column2  Column3  Column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [172]:
# This will Tell What is this Frame.
type(df)

pandas.core.frame.DataFrame

In [13]:
df[df['Column1']>2]

Column1  Column2  Column3  Column4
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [15]:
# This Will Give us all Info About our data Frame
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int32
 1   Column2  5 non-null      int32
 2   Column3  5 non-null      int32
 3   Column4  5 non-null      int32
dtypes: int32(4)
memory usage: 292.0+ bytes


In [19]:
# This will give a Clear Discription On Dataframe
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

# Indexing

In [178]:
# Using Column Name.
df[["Column1","Column2","Column3"]]

Column1  Column2  Column3
row1        0        1        2
row2        4        5        6
row3        8        9       10
row4       12       13       14
row5       16       17       18

In [22]:
# Using loc we will get complete row values.
df.loc[['row3','row2']]

Column1  Column2  Column3  Column4
row3        8        9       10       11
row2        4        5        6        7

In [26]:
# Using iloc we can get a Seperate Dataframe by our choice from the Original df.
# An Example that we only Want row:3,4 and coloumn:1,2 
df.iloc[2:4,0:2]

Column1  Column2
row3        8        9
row4       12       13

In [28]:
# An Example that we only want a dataframe in which row:all and Coloumn:1,4
df.iloc[0:,0::3]

Column1  Column4
row1        0        3
row2        4        7
row3        8       11
row4       12       15
row5       16       19

In [30]:
# If want a array from any df just use {.values} we will get a new array
df.iloc[0:,0::3].values

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15],
       [16, 19]])

# Operations:

In [33]:
# First Create a dataframe name df1 which contain 2 rows and 3 columns.
df1=pd.DataFrame(data=[[1,np.nan],[1,3,4]],index = ["row1","row2"],columns= ["Column1","Column2","Column3"])

In [35]:
df1.head()

Column1  Column2  Column3
row1        1      NaN      NaN
row2        1      3.0      4.0

In [37]:
df1.isnull().sum()==0

Column1     True
Column2    False
Column3    False
dtype: bool

In [41]:
df1['Column2'].value_counts()

Column2
3.0    1
Name: count, dtype: int64

In [200]:
df1['Column3'].unique()

array([nan,  4.])