# NumPy Arrays 

NumPy - Numerical Python
Advantages of Numpy : 
1. Allows Several Mathematical Operation
2. Faster Operations 

In [2]:
# calling Numpy in Pythin 
import numpy as np

In [3]:
# Change list into arrays using Numpy 
list1 = [1,2,3,4,5]
print(list1)
print(type(list1))

# it is a List now we will change into a array
arr1 = np.array(list1)
print(arr1)
print(type(arr1))
print(arr1.shape)

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
# How to Create Multi-Dimensional or We can Say 2D array
list1 = [1,2,3,5,6]
list2 = [5,6,7,8,9]
list3 = [3,3,4,6,9]
arr2D = np.array([list1,list2,list3])
print(arr2D)
print(type(arr2D))

[[1 2 3 5 6]
 [5 6 7 8 9]
 [3 3 4 6 9]]
<class 'numpy.ndarray'>


In [8]:
arr2D.shape    # This Will Tell You What is the Shape or We can Say Dimension of an Array
# Remembers Arrays Rows and Columns always counted from 0 .

(3, 5)

In [10]:
# Changing the index of an array.
print("Original array", arr1)
arr1[2] = 9    # for our 1D array.
print("array after index changing", arr1)
print("------------------------------------")
print("Original 2D array \n",  arr2D)
arr2D[2,1] = 12   # For our 2D array.
print("array after index changing \n", arr2D)



Original array [1 2 3 4 5]
array after index changing [1 2 9 4 5]
------------------------------------
Original 2D array 
 [[1 2 3 5 6]
 [5 6 7 8 9]
 [3 3 4 6 9]]
array after index changing 
 [[ 1  2  3  5  6]
 [ 5  6  7  8  9]
 [ 3 12  4  6  9]]


In [19]:
arr1  # First We have to call our 1D array.

array([1, 2, 9, 4, 5])

In [21]:
# Indexing in 1D array or arr
print(arr1[2])    # This will Directly tell what is the 3rd index in our 1st array.
print(arr1[2:])   # This will print the indexs from 3rd index to last index for 1D array.
print(arr1[::-1]) # This Will print a new Array which is reverse from the Previous one.
print(arr1[::2])  # This will give you a list in which indexes jumping in multiple of 2. 

9
[9 4 5]
[5 4 9 2 1]
[1 9 5]


In [23]:
arr2D  # First We have to call our 2D array.

array([[ 1,  2,  3,  5,  6],
       [ 5,  6,  7,  8,  9],
       [ 3, 12,  4,  6,  9]])

In [25]:
# Indexing in 2D array or arr1
print(arr2D[2,1])  # This will tell you what is in the index of {3,2} for arr2D. 
print(arr2D[:,1])  # This Will Give you a new array of complete 1 column of arr2D.
print(arr2D[1,:])  # This Will Give You a new array of complete 1 row of arr2D.

12
[ 2  6 12]
[5 6 7 8 9]


In [27]:
# using 1:  >>> this will del all items or we can we it will take all items except 1 row 
# using 1:3 >>> this will give us elements which are present on 1-2 in that column. 

print("Original array \n",arr2D)
print("New Array that what we get from original 2D array  ")
print(arr2D[1: ,1:3])  # This will Give you a 2D array of 2x2 

Original array 
 [[ 1  2  3  5  6]
 [ 5  6  7  8  9]
 [ 3 12  4  6  9]]
New Array that what we get from original 2D array  
[[ 6  7]
 [12  4]]


In [29]:
# using 2:   >>> this will del all items except 3rd row.
# using 2:5  >>> this will give us elemnts from 2 to 4 from 3rd column.
print("Original array \n",arr2D)
print("New Array that what we get from original 2D array  ")
print(arr2D[2: ,2:5])

Original array 
 [[ 1  2  3  5  6]
 [ 5  6  7  8  9]
 [ 3 12  4  6  9]]
New Array that what we get from original 2D array  
[[4 6 9]]


In [31]:
# using :   >>> this will take all the items from 0 to 2 row.
# using 3:  >>> this will give us elemnts from .
print("Original array \n",arr2D)
print("New Array that what we get from original 2D array  ")
print(arr2D[:,3:]) 

Original array 
 [[ 1  2  3  5  6]
 [ 5  6  7  8  9]
 [ 3 12  4  6  9]]
New Array that what we get from original 2D array  
[[5 6]
 [8 9]
 [6 9]]


In [33]:
# using :   >>> this will take all the items from 0 to 2 row.
# using 0: :4  >>> this will give us elemnts from 1st coloumn and last column.
print("Original array \n",arr2D)
print("New Array that what we get from original 2D array  ")
print(arr2D[:,0::4])

Original array 
 [[ 1  2  3  5  6]
 [ 5  6  7  8  9]
 [ 3 12  4  6  9]]
New Array that what we get from original 2D array  
[[1 6]
 [5 9]
 [3 9]]


In [35]:
arr1  # This will print our New Array.

array([1, 2, 9, 4, 5])

In [39]:
# If want a array from our arr which is greater than 2 then:
print(arr1>2)    # This will give us Booleans values 
arr1[arr1>2]      # This will create a new array only elements which is greater than 2.

[False False  True  True  True]


array([9, 4, 5])

In [41]:
# Changing the dimension of arr1 (3X5) to (5X3)
print("Original array \n",arr2D)
print("New Array that what we get from original 2D array  ")
print(arr2D.reshape(5,3))

Original array 
 [[ 1  2  3  5  6]
 [ 5  6  7  8  9]
 [ 3 12  4  6  9]]
New Array that what we get from original 2D array  
[[ 1  2  3]
 [ 5  6  5]
 [ 6  7  8]
 [ 9  3 12]
 [ 4  6  9]]


In [43]:
# Creating a 1D array
arr2 = np.arange(1,16,2)  # Numpy Directly create a array by step value.
print(arr2)

# Now we can also reshape the array by our choice.
arr3 = arr2.reshape(2,4)    # reshaping into dimension of 2X4.
print(arr3)  

arr4 = arr2.reshape(4,2)    # Reshaping into dimension of 4X2
print(arr4)               

[ 1  3  5  7  9 11 13 15]
[[ 1  3  5  7]
 [ 9 11 13 15]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [45]:
# Yes Bhai !!!!
print("Original Array",arr2)
arr5 = arr2*arr2  # our 1st array is multiply by itself and give us a new array.
print("New Array ",arr5)

print("-------------------------------------------")

print("Original Array",arr2)
arr6 = arr2 *2   # our 1st array is multiply by 2 and give us a new array.
print("New Array ",arr6)

Original Array [ 1  3  5  7  9 11 13 15]
New Array  [  1   9  25  49  81 121 169 225]
-------------------------------------------
Original Array [ 1  3  5  7  9 11 13 15]
New Array  [ 2  6 10 14 18 22 26 30]


In [47]:
arr7 = np.ones((3,3))
print("Ones array of 3x3 \n",arr7)

arr8 = np.zeros((3,3))
print("Zeros array of 3x3 \n",arr8)

Ones array of 3x3 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Zeros array of 3x3 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [49]:
arr9 = np.full((3,4),3)
print(arr9)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [51]:
arr10 = np.eye(4)
print(arr10)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [53]:
# array with random values 
arr11 = np.random.random((2,4))
print(arr11)

# we can see that we get values only from 0 to 1 

[[0.96150886 0.84271576 0.82420734 0.42657851]
 [0.18386779 0.70754119 0.83330265 0.96627227]]


In [55]:
# array with intger value 
arr12 = np.random.randint(10,100,(2,4))
print(arr12)

[[87 86 55 49]
 [59 80 63 75]]


In [57]:
arr13 = np.linspace(10,30,5)
print(arr13)

[10. 15. 20. 25. 30.]


In [59]:
arr13 = np.arange(10,30,5)    #  remember that the value you will got is (n-1)
print(arr13)

[10 15 20 25]


In [61]:
arr14 = np.random.randint(1,100,25).reshape(5,5)
print(arr14)
print("Size of The array",arr14.size)

[[75 97 73 89 11]
 [45 75  3  4 61]
 [22 60 24 82 44]
 [32 58 96 39 81]
 [25  9 30 22 99]]
Size of The array 25
